import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { Pipeline, TreeWalker, configureDocConverter, BinaryKit } from '../../index';

// Generated by LibreOffice's MS Word 97 filter, not hwpkit. See fixtures README.
const fixture = new Uint8Array(readFileSync(resolve('tests/fixtures/legacy-word97.doc')));
const tokens = ['제목 Alpha', '본문 Beta', '한글 표시', '항목', 'Gamma', 'Delta', '마지막 문단 Omega'];
afterEach(() => configureDocConverter());

/** Minimal MS-CFB v3 package: two regular streams, no encoder dependency. */
function makePieceFixture(): Uint8Array {
  const file = new Uint8Array(19 * 512);
  const v = new DataView(file.buffer);
  file.set([0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1]);
  v.setUint16(24, 0x3e, true); v.setUint16(26, 3, true); v.setUint16(28, 0xfffe, true);
  v.setUint16(30, 9, true); v.setUint16(32, 6, true);
  v.setUint32(44, 1, true); v.setUint32(48, 1, true); v.setUint32(56, 4096, true);
  v.setUint32(60, 0xfffffffe, true); v.setUint32(68, 0xfffffffe, true);
  file.fill(0xff, 76, 512); v.setUint32(76, 0, true);
  file.fill(0xff, 512, 1024);
  v.setUint32(512, 0xfffffffd, true); v.setUint32(516, 0xfffffffe, true);
  for (let sector = 2; sector < 18; sector++) v.setUint32(512 + sector * 4, sector === 9 || sector === 17 ? 0xfffffffe : sector + 1, true);
  const directory = (index: number, name: string, type: number, start: number, size: number, child = -1, right = -1) => {
    const base = 1024 + index * 128;
    for (let i = 0; i < name.length; i++) v.setUint16(base + i * 2, name.charCodeAt(i), true);
    v.setUint16(base + 64, (name.length + 1) * 2, true); file[base + 66] = type; file[base + 67] = 1;
    v.setInt32(base + 68, -1, true); v.setInt32(base + 72, right, true); v.setInt32(base + 76, child, true);
    v.setUint32(base + 116, start, true); v.setUint32(base + 120, size, true);
  };
  directory(0, 'Root Entry', 5, 0xfffffffe, 0, 1);
  directory(1, '0Table', 2, 10, 4096, -1, 2);
  directory(2, 'WordDocument', 2, 2, 4096);
  const word = 3 * 512, table = 11 * 512;
  v.setUint16(word, 0xa5ec, true); v.setUint16(word + 2, 0xc1, true);
  v.setUint16(word + 32, 14, true); v.setUint16(word + 62, 22, true);
  v.setUint16(word + 152, 93, true);
  const ascii = 'ASCII \x80\r'; // FcCompressed maps 0x80 to EURO SIGN.
  const unicode = '한글\r';
  v.setUint32(word + 76, ascii.length + unicode.length, true);
  // Include one Prc before Pcdt to cover variable CLX layout.
  v.setUint32(word + 418, 0, true); v.setUint32(word + 422, 36, true);
  file[table] = 1; v.setUint16(table + 1, 0, true); file[table + 3] = 2; v.setUint32(table + 4, 28, true);
  v.setUint32(table + 8, 0, true); v.setUint32(table + 12, ascii.length, true);
  v.setUint32(table + 16, ascii.length + unicode.length, true);
  v.setUint32(table + 22, 0x40000000 | (1024 * 2), true);
  v.setUint32(table + 30, 2048, true);
  for (let i = 0; i < ascii.length; i++) file[word + 1024 + i] = ascii.charCodeAt(i);
  for (let i = 0; i < unicode.length; i++) v.setUint16(word + 2048 + i * 2, unicode.charCodeAt(i), true);
  return file;
}

describe('legacy Word DOC input', () => {
  it('reads compressed/Unicode pieces and a Prc from the selected 0Table stream', async () => {
    const result = await Pipeline.open(makePieceFixture()).inspect();
    if (!result.ok) throw new Error(result.error);
    expect(new TreeWalker().extractText(result.data)).toBe('ASCII €한글');
  });
  it.each(['hwp', 'hwpx', 'docx', 'md', 'html'])('auto-detects DOC and converts to %s', async format => {
    const before = fixture.slice();
    const result = await Pipeline.open(fixture).to(format);
    if (!result.ok) throw new Error(result.error);
    expect(result.warns.join(' ')).toContain('DOC 기본 읽기');
    const parsed = await Pipeline.open(result.data, format).inspect();
    if (!parsed.ok) throw new Error(parsed.error);
    const text = new TreeWalker().extractText(parsed.data);
    for (const token of tokens) expect(text).toContain(token);
    expect(fixture).toEqual(before);
  });

  it('supports explicit .DOC and File input', async () => {
    const pipeline = await Pipeline.openAsync(new File([fixture], 'legacy.DOC'));
    expect((await pipeline.inspect()).ok).toBe(true);
    expect((await Pipeline.open(fixture, '.DOC').inspect()).ok).toBe(true);
    expect((await Pipeline.open(fixture, 'application/msword').inspect()).ok).toBe(true);
  });

  it('uses a configured DOCX bridge without a lossy text fallback', async () => {
    const converted = await Pipeline.open('서식 **보존**').to('docx');
    if (!converted.ok) throw new Error(converted.error);
    const bridge = vi.fn(async () => converted.data);
    configureDocConverter(bridge);
    const result = await Pipeline.open(fixture).inspect();
    if (!result.ok) throw new Error(result.error);
    expect(bridge).toHaveBeenCalledOnce();
    expect(new TreeWalker().extractText(result.data)).toContain('서식 보존');
    expect(result.warns.join(' ')).not.toContain('기본 읽기');
  });

  it('reports bridge errors instead of silently discarding formatting', async () => {
    configureDocConverter(async () => { throw new Error('office unavailable'); });
    const result = await Pipeline.open(fixture).to('hwp');
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.error).toContain('office unavailable');
  });

  it('rejects encrypted DOC before invoking a bridge', async () => {
    const bytes = fixture.slice();
    const word = BinaryKit.parseCfb(bytes).get('WordDocument')!;
    // Locate the independently generated FIB even when WordDocument uses mini FAT.
    const offset = bytes.findIndex((_, i) => word.subarray(0, 16).every((b, n) => bytes[i + n] === b));
    expect(offset).toBeGreaterThan(0);
    const view = new DataView(bytes.buffer);
    view.setUint16(offset + 10, view.getUint16(offset + 10, true) | 0x100, true);
    const bridge = vi.fn();
    configureDocConverter(bridge);
    const result = await Pipeline.open(bytes).inspect();
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.error).toContain('암호화');
    expect(bridge).not.toHaveBeenCalled();
  });

  it('rejects missing/truncated containers and cyclic FAT chains without hanging', async () => {
    for (const bytes of [new Uint8Array(0), fixture.slice(0, 100), fixture.slice(0, 512)]) {
      expect((await Pipeline.open(bytes, 'doc').inspect()).ok).toBe(false);
    }
    const bytes = fixture.slice();
    const view = new DataView(bytes.buffer);
    const directorySector = view.getUint32(48, true);
    const fatSector = view.getUint32(76, true);
    view.setUint32((fatSector + 1) * 512 + directorySector * 4, directorySector, true);
    expect((await Pipeline.open(bytes, 'doc').inspect()).ok).toBe(false);
  });
});
